### ISSUE TITLE
Training result

### ISSUE THREAD

**Issue by jahaniam** [saeid-h/bts-fully-tf#1]
Nice work. Did you train your model using your code and compare it with original bts v1? I'm curious to see the difference!

Thank you,
Ali

**Comment by saeid-h** [comment]
Thank you. Not yet. I have changed more in my private repo and it's being trained on another dataset. I will try it on holidays.

**Comment by saeid-h** [comment]
Ali jon (@a-jahani),
Here is my trained model on [Google Drive](https://drive.google.com/file/d/1KgLFgZa9U4X7Kq1_U908idFo_GBfu04d/view?usp=sharing)

The results are close to the original model:
d1,      d2,      d3,  AbsRel,   SqRel,    RMSE, RMSElog,   SILog,   log10
  0.880,   0.978,   0.996,   0.113,   0.060,   0.356,   0.142,  11.333,   0.048

**Comment by jahaniam** [comment]
Thanks Saeid
