### ISSUE TITLE
Question about information required for training other than RGB Depth data

### ISSUE THREAD

**Issue by mohammad-saber** [saeid-h/bts-fully-tf#2]
Thank you very much for sharing your great code. I have a question about training process.

Is there any additional information other than RGB and depth required for training? (Example: camera intrinsic, extrinsic, or other project specific information).

Thank you very much for your help.

**Comment by saeid-h** [comment]
You need the camera's focal length.

**Comment by mohammad-saber** [comment]
May I ask another question about training?

Is the training process Supervised or Self-Supervised?

**Comment by mohammad-saber** [comment]
May I ask another question in this regard?
What is purpose of using "camera's focal length"?

**Comment by saeid-h** [comment]
They use it to project 3D points on the 2D plane. The related paper is available here: https://arxiv.org/pdf/1907.10326.pdf 
If you have more questions please feel free to contact me or the author by email.
